package models

import (
	"time"
)

type Student struct {
	Id        int    // Database autogenerated Id number.
	IdNumber  string `sql:"size:20; unique_index"` // Honduran Document Id number.
	Email     string `sql:"size:60; unique_index"`
	FirstName string `sql:"size:60"`
	LastName  string `sql:"size:60"`
	Status    int
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt time.Time
}
